# Generated by Django 5.2.3 on 2025-07-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_deliveryassignment_delete_deliverytracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='order',
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trips', to='products.order'),
            preserve_default=False,
        ),
    ]
