# Generated by Django 5.2.3 on 2025-07-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_deliveryassignment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='order',
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='orders',
            field=models.ManyToManyField(to='products.order'),
        ),
    ]
