# Generated by Django 5.2.3 on 2025-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_deliveryassignment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('CASH', 'Cash on Delivery')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('COD', 'Cash on Delivery'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
